title: 程序员思维
email: leric.zhang@gmail.com
description: >-
  用代码的逻辑理解世界. 
baseurl: ""
url: "https://leric.github.io"
github_username:  leric

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
